TRUNCATE TABLE ESPM_STOCK;
DELETE FROM ESPM_PRODUCT;
INSERT INTO ESPM_PRODUCT(PRODUCT_ID,PRODUCT_NAME,SHORT_DESCRIPTION,PRODUCT_CATEGORY,WEIGHT,WEIGHT_UNIT,PRICE,CURRENCY_CODE,DIMENSION_WIDTH,DIMENSION_HEIGHT,DIMENSION_DEPTH,DIMENSION_UNIT,PICTURE_URL) VALUES('1', 'TV', 'TV', 'TV', 1.0, 'KG',2.0,'EUR',2.0,2.0,2.0,'M','');
INSERT INTO ESPM_PRODUCT(PRODUCT_ID,PRODUCT_NAME,SHORT_DESCRIPTION,PRODUCT_CATEGORY,WEIGHT,WEIGHT_UNIT,PRICE,CURRENCY_CODE,DIMENSION_WIDTH,DIMENSION_HEIGHT,DIMENSION_DEPTH,DIMENSION_UNIT,PICTURE_URL) VALUES('2', 'DVD', 'DVD', 'DVD', 1.0, 'KG',2.0,'EUR',2.0,2.0,2.0,'M','');