--DROP TABLE ESPM_SALES_ORDER;
--CREATE TABLE IF NOT EXISTS ESPM_SALES_ORDER(SALES_ORDER_ID PRIMARY KEY, CUSTOMER_EMAIL NOT NULL, PRODUCT_ID NOT NULL,
--CURRENCY_CODE VARCHAR(5) NOT NULL, GROSS_AMOUNT DECIMAL, NET_AMOUNT DECIMAL, TAX_AMOUNT DECIMAL, LIFECYCLE_STATUS VARCHAR(1), LIFECYCLE_STATUS_NAME VARCHAR,
--QUANTITY DECIMAL, QUANTITY_UNIT VARCHAR(10), DELIVERY_DATE DATE, CREATED_AT DATE);
TRUNCATE TABLE ESPM_SALES_ORDER;

INSERT INTO ESPM_SALES_ORDER(SALES_ORDER_ID, CUSTOMER_EMAIL,PRODUCT_ID, CURRENCY_CODE, GROSS_AMOUNT, NET_AMOUNT, TAX_AMOUNT, LIFECYCLE_STATUS, LIFECYCLE_STATUS_NAME, QUANTITY, QUANTITY_UNIT, DELIVERY_DATE, CREATED_AT) VALUES ('1','customer@gmail.com','1','DLR',100.0,90.0,10.0,'1','',1.0,'KG','2018-01-01','2018-01-01');
INSERT INTO ESPM_SALES_ORDER(SALES_ORDER_ID, CUSTOMER_EMAIL,PRODUCT_ID, CURRENCY_CODE, GROSS_AMOUNT, NET_AMOUNT, TAX_AMOUNT, LIFECYCLE_STATUS, LIFECYCLE_STATUS_NAME, QUANTITY, QUANTITY_UNIT, DELIVERY_DATE, CREATED_AT) VALUES ('2','customer2@gmail.com','1','DLR',100.0,90.0,10.0,'1','',1.0,'KG','2018-01-01','2018-01-01');
--INSERT INTO ESPM_SALES_ORDER VALUES ('3','2','1','DLR',100.0,90.0,10.0,'1','',1.0,'KG','2018-01-01','2018-01-01');

