--DROP TABLE ESPM_SALES_ORDER;
--CREATE TABLE IF NOT EXISTS ESPM_SALES_ORDER(SALES_ORDER_ID PRIMARY KEY, CUSTOMER_EMAIL NOT NULL, PRODUCT_ID NOT NULL,
--CURRENCY_CODE VARCHAR(5) NOT NULL, GROSS_AMOUNT DECIMAL, NET_AMOUNT DECIMAL, TAX_AMOUNT DECIMAL, LIFECYCLE_STATUS VARCHAR(1), LIFECYCLE_STATUS_NAME VARCHAR,
--QUANTITY DECIMAL, QUANTITY_UNIT VARCHAR(10), DELIVERY_DATE DATE, CREATED_AT DATE);
TRUNCATE TABLE ESPM_SALES_ORDER;
INSERT INTO ESPM_SALES_ORDER(SALES_ORDER_ID, CUSTOMER_EMAIL, PRODUCT_ID, CURRENCY_CODE, GROSS_AMOUNT, NET_AMOUNT, TAX_AMOUNT, LIFECYCLE_STATUS, LIFECYCLE_STATUS_NAME, QUANTITY, QUANTITY_UNIT, DELIVERY_DATE, CREATED_AT, NOTE, PRODUCT_NAME) values 
('ac4e58d8-60f2-4af2-8f15-548e96729a3f','testcustomer@gmail.com','HT-1000','EUR',1500.0,1650.0,150.0,'N','New',2.0,'EA','2022-09-01','2022-09-09','','Notebook Basic 15');

